---

- name: Get Service Accounts informations
  gcp_iam_service_account_info:
    project: "{{ lookup('env','GCLOUD_PROJECT') }}"
    auth_kind: serviceaccount
    service_account_file: "{{ lookup('env','GOOGLE_APPLICATION_CREDENTIALS') }}"
  register: gcp_sa

- name: Get Ansible service account ID & Jump Host name
  set_fact:
    ansible_sa_id: '{{ gcp_sa.resources | json_query(query) | first }}'
  vars:
    query: "[?displayName=='{{ ansible_sa_name }}'].uniqueId"

- name: Set jump_mode if jump_group exists
  set_fact:
    jump_mode: yes
  when: "'{{ jump_group }}' in groups"

- import_tasks: 'ssh_jump.yml'
  when: jump_mode | default(False) | bool

- name: Generate SSH config
  template:
    src: '{{ template_ssh_config }}'
    dest: '{{ ssh_files_path }}/{{ ssh_config_name }}'
    mode: 0644

- name: Refresh inventory
  meta: refresh_inventory
